new ci test 2

diff --git a/.pipelines/YS-CI.yml b/.pipelines/YS-CI.yml
--- a/.pipelines/YS-CI.yml
+++ b/.pipelines/YS-CI.yml
@@ -25,25 +25,25 @@ stages:
 - stage: Get_Pipeline_ID
   jobs:
   - job: "Get_Pipeline_ID"
-      condition: and(succeeded(), eq(coalesce(variables['auto-trigger-training'], 'true'), 'true'))
-      displayName: "Get Pipeline ID for execution"
-      container: mlops
-      timeoutInMinutes: 0
-      steps:
-      - task: AzureCLI@1
-        inputs:
-          azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-          scriptLocation: inlineScript
-          workingDirectory: $(Build.SourcesDirectory)
-          inlineScript: |
-            set -e # fail on error
-            export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-            python -m ml_service.pipelines.run_train_pipeline --output_pipeline_id_file "pipeline_id.txt" --skip_train_execution
-            # Set AMLPIPELINEID variable for next AML Pipeline task in next job
-            AMLPIPELINEID="$(cat pipeline_id.txt)"
-            echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$AMLPIPELINEID"
-        name: 'getpipelineid'
-        displayName: 'Get Pipeline ID'
+    condition: and(succeeded(), eq(coalesce(variables['auto-trigger-training'], 'true'), 'true'))
+    displayName: "Get Pipeline ID for execution"
+    container: mlops
+    timeoutInMinutes: 0
+    steps:
+    - task: AzureCLI@1
+      inputs:
+        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+        scriptLocation: inlineScript
+        workingDirectory: $(Build.SourcesDirectory)
+        inlineScript: |
+          set -e # fail on error
+          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+          python -m ml_service.pipelines.run_train_pipeline --output_pipeline_id_file "pipeline_id.txt" --skip_train_execution
+          # Set AMLPIPELINEID variable for next AML Pipeline task in next job
+          AMLPIPELINEID="$(cat pipeline_id.txt)"
+          echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$AMLPIPELINEID"
+      name: 'getpipelineid'
+      displayName: 'Get Pipeline ID'
 
 - stage: Cycle_Data
   jobs:
