Updated YS-First-Ingestion.yml

diff --git a/.pipelines/YS-First-Ingestion.yml b/.pipelines/YS-First-Ingestion.yml
--- a/.pipelines/YS-First-Ingestion.yml
+++ b/.pipelines/YS-First-Ingestion.yml
@@ -22,24 +22,20 @@ variables:
 pool:
   vmImage: ubuntu-latest
 
-stages:
-- stage: 'First_Ingestion'
-  displayName: 'First Ingestion'
-  jobs:
-  - job: "First_Ingestion_Pipeline"
-    displayName: "First Ingestion Pipeline"
-    container: mlops
-    timeoutInMinutes: 0
-    steps:
-    - template: code-quality-template.yml
-    - task: AzureCLI@1
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          # Invoke the Python code for first data ingestion
-          python -m code.first_ingestion.py
-      displayName: 'First code ingestion'
+jobs:
+- job: "First_Ingestion_Pipeline"
+  displayName: "First Ingestion Pipeline"
+  container: mlops
+  timeoutInMinutes: 0
+  steps:
+  - task: AzureCLI@1
+    inputs:
+      azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+      scriptLocation: inlineScript
+      workingDirectory: $(Build.SourcesDirectory)
+      inlineScript: |
+        set -e # fail on error
+        export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+        # Invoke the Python code for first data ingestion
+        python -m code.first_ingestion.py
+    displayName: 'First code ingestion'
