Removed testing on pipeline

diff --git a/.pipelines/YS-Train-Register.yml b/.pipelines/YS-Train-Register.yml
--- a/.pipelines/YS-Train-Register.yml
+++ b/.pipelines/YS-Train-Register.yml
@@ -21,24 +21,20 @@ variables:
 pool:
   vmImage: ubuntu-latest
 
-stages:
-- stage: 'Training_and_Registering_Model'
-  displayName: 'Training and Registering Model'
-  jobs:
-  - job: "Training_Model_Pipeline"
-    displayName: "Training and Registering Model Pipeline"
-    container: mlops
-    timeoutInMinutes: 0
-    steps:
-    - template: code-quality-template.yml
-    - task: AzureCLI@1
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          # Invoke the Python code for first data ingestion
-          python -m code.train
-      displayName: 'Training and registering model'
+jobs:
+- job: "Training_Model_Pipeline"
+  displayName: "Training and Registering Model Pipeline"
+  container: mlops
+  timeoutInMinutes: 0
+  steps:
+  - task: AzureCLI@1
+    inputs:
+      azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+      scriptLocation: inlineScript
+      workingDirectory: $(Build.SourcesDirectory)
+      inlineScript: |
+        set -e # fail on error
+        export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+        # Invoke the Python code for first data ingestion
+        python -m code.train
+    displayName: 'Training and registering model'
